### ISSUE TITLE
Topic hardcoded to DDEServer

### ISSUE THREAD

**Issue by Sam-Hall** [Code-Artist/DDEApp#1]
I was hoping to be able to use DdeAppClient to connect to an existing server, but it seems you've hard coded the topic to "DDEServer". Any chance of publishing the C# source code under MIT license?

**Comment by Code-Artist** [comment]
Hello Sam,

Feel free to modify the code as per your need.
LICENSE file added to project for your reference.

Regards,
Code Artist

**Comment by Sam-Hall** [comment]
Much appreciated!
